### ISSUE TITLE
English for GUI

### ISSUE THREAD

**Issue by loitranit** [killkimno/MORT#1]
- Best project - please support english language for GUI.
Thank you!

**Comment by killkimno** [comment]
Thanks for your comments.
I will try to apply the English GUI.

**Comment by fernandom241** [comment]
Just want to say this is an awesome app, i really need this heck if you sell it on steam i'll buy it. it'll be better if there is an english gui and can translate to english so that finally i could play games that does not support english language.

**Comment by killkimno** [comment]
Currently working.
It takes at least two weeks.

maybe more than a month

**Comment by killkimno** [comment]
https://github.com/killkimno/MORT/releases/tag/1.242

English GUI is supported from 1.242v.

There are many places that have been translated incorrectly because the translation is not perfect yet.
Please tell me where it's not translated or where it's wrong

https://github.com/killkimno/MORT/issues/3

**Comment by amymor** [comment]
> @loitranit @fernandom241 https://github.com/killkimno/MORT/releases/tag/1.242
> 
> English GUI is supported from 1.242v.
> 
> There are many places that have been translated incorrectly because the translation is not perfect yet. Please tell me where it's not translated or where it's wrong
> 
> #3
![Screenshot (26)](https://github.com/user-attachments/assets/fa718aef-44ea-43e2-a501-f59b76379400)

**Comment by amymor** [comment]
![0084](https://github.com/user-attachments/assets/e40ac357-4bb1-48c7-a625-e8696c60cfb6)

**Comment by killkimno** [comment]
Thanks for the tip! The two UIs below are not translated because they have no use for anyone other than Koreans.
I will apply some of the missing translations in the next patch.
