### ISSUE TITLE
Russian interface language

### ISSUE THREAD

**Issue by KirpichKrasniy** [killkimno/MORT#11]
Hello, I want to help translate your program into Russian. How can I do it? Can you give me files with elements of the program, which I can translate and send you, so you can add Russian to the interface?

I can't promise that the translation will be perfect, but it will be easier for Russian-speaking users to understand the program. I can also translate the githab pages into Russian.

**Comment by killkimno** [comment]
hello! Thank you for your interest.
There is currently no configuration for collaboration.

UI localization is in this Sheet
https://docs.google.com/spreadsheets/d/1T50DQBgLF1k3sPduPMe7MluFcxukc58qye0dX_QKC1g/edit#gid=0.

Add RU tab and I will apply

Readm page
https://github.com/killkimno/MORT/blob/master/README.base.md?plain=1

How to insert a translation


tex text text
text ....


Automatically generate documents using this program.

https://github.com/killkimno/CSharp-Multilingual-Markdown-Generator

I will apply if you send me

however Adding localization is currently a low priority.
But i'll work on it soon

**Comment by KirpichKrasniy** [comment]
> I will apply if you send me




 I get it. I will send you the translation when it is ready.
Can I just post it here?

**Comment by KirpichKrasniy** [comment]
![image](https://github.com/killkimno/MORT/assets/109726461/77fea11f-8587-4519-9f88-e44aa45b08ea)
I take it you don't need to touch the second tab?

**Comment by killkimno** [comment]
yes. '시트3' is auto translate sheet
so you can modify 시트3

**Comment by killkimno** [comment]
Applied to latest version
