### ISSUE TITLE
Add a custom API based on http request like follow

### ISSUE THREAD

**Issue by liuchuhan1** [killkimno/MORT#13]

**Comment by killkimno** [comment]
thanks for the suggestion

ill research add custom api

**Comment by liuchuhan1** [comment]
HTTP POST a JSON like this  :
{
  "name": "ja-en", // API name, classify the api, can be ignore
  "text": "これは翻訳インタフェースです", // the text to be translated
  "destination": "en", // destination language, the short one like ko,ja,ru
  "source": "" // sorce language type，it may be undefined, and your interface needs to automatically determine the language
}

 the return can be like this JSON:
{
  "text": "これは翻訳インタフェースです",//the source ext
  "from": "ja", //the source text type
  "to": "en", //the destination text type
  "result": ["This is a translation interface"]  //the result is an array of string because  the source text may contain many paragraphs, the proccess will be slow, so the source text should be cutoff by nextline("/n"), every paragraph can be a member of the array.
}

then you just need to use the result array.

above is only a sample, any other kind is also OK like send GET request with parameters, you just need to add the API, offer a textarea to fill the Inerface Address like "http://localhost:8080/translator" and choose source lang/destination lang , then show what MORT will request and what return JSON it can resolve in README like what I offer above.
To finetune the custom server is the work the users should do, maybe I will publish a guide how to build a local translate server by Python.

**Comment by liuchuhan1** [comment]
> thanks for the suggestion
> 
> ill research add custom api

hello, I changed the naverapi to custom api, but failed when building, so can I send you the .cs



using RestSharp;
using System;
using System.Collections.Generic;

namespace MORT
{

    class NaverTranslateAPI
    {
        public static NaverTranslateAPI instance;
        private string transCode;
        private string resultCode;
        private string apiType= "NMT";
        private string url;
        private struct ToTrans
        {
            public string name;
            public string text;
            public string target;
            public string source;
        }
        private void Init(TransManager.NaverKeyData data)
        {
            this.url = data.id;//////use idKey to transit the translate interface server address parameter like http://127.0.0.1:16888/translater
        }
        public void ChangeValue(string idKey, string secretKey, bool isPaid = false)
        {
            this.url = idKey;//////use idKey to transit the translate interface server address parameter like http://127.0.0.1:16888/translater
        }

        public string GetAPIType()
        {
            return apiType;
        }

        public void SetTransCode(string transCode, string resultCode)
        {
            this.transCode = transCode;
            this.resultCode = resultCode;
        }

        public string GetResult(string original, ref bool isError)
        {
            /*
            //TEST
            if(!isPaid)
            {
                TransManager.Instace.SetState(TransManager.NaverKeyData.eState.Error);
                if (TransManager.Instace.naverKeyList.Count > 1)
                {
                    TransManager.NaverKeyData data = TransManager.Instace.GetNextNaverKey();
                    Init(data);
                    return "\n[" + (TransManager.Instace.currentNaverIndex + 1).ToString() + "]번째 키를 활성화 합니다. ";
                }
            }
            */
            //줄바꿈은 %0A 임
            string trim = original.Replace(" ", "");
            trim = trim.Replace(Environment.NewLine, "");
            if (trim == "")
            {
                return "";
            }

            string result = "";
            var client = new RestClient(url);
            var request = new RestRequest(Method.POST);
            request.AddHeader("content-type", "application/json"); //폼 형식
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("charset", "UTF-8");

            //Here generate a object of the JSON which  sent to server
            ToTrans toTrans = new ToTrans
            {
                name = transCode + resultCode,
                text = original,
                target = transCode,
                source = resultCode
            };

            request.AddJsonBody(toTrans);


            IRestResponse response = client.Execute(request);
            IDictionary<string, object> dic = (IDictionary<string, object>)SimpleJson.DeserializeObject(response.Content);
            //RestSharp.Deserializers.JsonDeserializer deserial = new RestSharp.Deserializers.JsonDeserializer();
            Dictionary<string, object> dic = deserial.Deserialize<Dictionary<string, object>>(response);
            string re = deserial.Deserialize<string>(response);
            Util.ShowLog(re);

            /*
            if(!dic.ContainsKey("errorMessage"))
            dic.Add("errorMessage", "ddd");
            if (!dic.ContainsKey("errorCode"))
                dic.Add("errorCode", " ssss");
                */

            //무료 API 에러
            if (dic.ContainsKey("errorMessage"))
            {
                isError = true;
                result = (string)dic["errorMessage"];

                if (dic.ContainsKey("errorCode"))
                {
                    string error = (string)dic["errorCode"];
                    result += "\n Error Cdoe : " + error;

                    if (error == "010")
                    {
                        //초과
                        TransManager.Instace.SetState(TransManager.NaverKeyData.eState.Limit);
                    }
                    else if (error == "024")
                    {
                        //인증실패 사용할 수 없음
                        TransManager.Instace.SetState(TransManager.NaverKeyData.eState.Error);
                    }

                    if (TransManager.Instace.naverKeyList.Count > 1)
                    {
                        TransManager.NaverKeyData data = TransManager.Instace.GetNextNaverKey();
                        Init(data);
                        result += "\n[" + (TransManager.Instace.currentNaverIndex + 1).ToString() + "]번째 키를 활성화 합니다. ";
                    }
                }
                //result = "1";
            }
            //유료 API 에러
            else if(dic.ContainsKey("error"))
            {
                Dictionary<string, object> errorDic = (Dictionary<string, object>)dic["error"];
                isError = true;
                result = (string)errorDic["message"];

                if (errorDic.ContainsKey("errorCode"))
                {
                    string error = (string)errorDic["errorCode"];
                    result += "\n Error Cdoe : " + error;

                    if (error == "010")
                    {
                        //초과
                        TransManager.Instace.SetState(TransManager.NaverKeyData.eState.Limit);
                    }
                    else if (error == "200")
                    {
                        //인증실패 사용할 수 없음
                        TransManager.Instace.SetState(TransManager.NaverKeyData.eState.Error);
                    }

                    if (TransManager.Instace.naverKeyList.Count > 1)
                    {
                        TransManager.NaverKeyData data = TransManager.Instace.GetNextNaverKey();
                        Init(data);
                        result += "\n[" + (TransManager.Instace.currentNaverIndex + 1).ToString() + "]번째 키를 활성화 합니다. ";
                    }
                }
            }

            else if (dic.ContainsKey("result"))
            {
                JsonArray resultarray = (JsonArray)dic["result"];
                for(int i = 0; i < resultarray.Count; i++)
                {
                    result +=  (string)resultarray[i];
                }
            }
            //result += "\n" + TransManager.Instace.currentNaverIndex;
            return result;
        }
    }
}

**Comment by killkimno** [comment]
Thanks ill try it.

if you build faild

1. debug mode not support. change to relase mode
2. set x64
3. if still build fail check requiement file -> Relase Folder -> unzip last realse file( https://github.com/killkimno/MORT/releases/download/1.256/MORT.1.256v.-.20230617.zip)
- This is a problem caused by moving and deleting files in the Release folder in the build settings.

**Comment by liuchuhan1** [comment]
> Thanks ill try it. but i dont have local translate server. how can i test it?
> 
> if you build faild
> 
> 1. debug mode not support. change to relase mode
> 2. set x64
> 3. if still build fail check requiement file -> Relase Folder -> unzip last realse file( https://github.com/killkimno/MORT/releases/download/1.256/MORT.1.256v.-.20230617.zip)
> 
> * This is a problem caused by moving and deleting files in the Release folder in the build settings.

Thanks, I have success built and it can work right sometimes, but the refresh rate is to high that the Python based translate server cant translate so fast though I turn the processing speed to lowest, maybe it was because of my rubish graphic card NVIDIA RTX 3060 Laptop , so it return a 500 status code, i will try to fix this issue by guess the CUDA's core is busy or idle to return a  message and then in the NaverTranslateAPI.cs to determin whether to await for some seconds. I will keep this issue until it work well, and if you have spare time , you can add this function sololy without change  the NAVERAPI.

**Comment by liuchuhan1** [comment]
> Thanks ill try it. but i dont have local translate server. how can i test it?
> 
> if you build faild
> 
> 1. debug mode not support. change to relase mode
> 2. set x64
> 3. if still build fail check requiement file -> Relase Folder -> unzip last realse file( https://github.com/killkimno/MORT/releases/download/1.256/MORT.1.256v.-.20230617.zip)
> 
> * This is a problem caused by moving and deleting files in the Release folder in the build settings.

tomorrow I will send the local server source code here

**Comment by killkimno** [comment]
Tomorrow I'll create a branch for custom api.

**Comment by liuchuhan1** [comment]
Thank you, I built success, but it cant work well, there are some issues:
1. when select translate custom api, there is no text area to fill the source/target language type and url.
![image](https://github.com/killkimno/MORT/assets/80662530/16c64d5f-8fc1-4a49-ac30-2325582aac4f)
2. I find that you init the language type with en to ko, and url http://localhost:8080/translator, but my server cant get the value of source and target in the JSON which shows "NONE".
![image](https://github.com/killkimno/MORT/assets/80662530/1a5d76a8-cdaa-45ce-878a-e049f349e852)
3.I set the server to ignore the source and target but only translate the text, and there is another issue show that the type convert is error, it maybe the dictionary k,v convert  issue:
errorCode ->int
errorMessage-> string
guess the resultObject is JsonArray
so, I change the CustomAPI.cs to fix the 3 issues, and it can work will. The translate speed is OK as well.
Changed CustomAPI.cs is following:

using RestSharp;
using System;
using System.Collections.Generic;

namespace MORT.TransAPI
{
    public class CustomAPI
    {
        private string _url;
        private string _transCode;
        private string _resultCode;

        private struct ToTrans
        {
            public string name;
            public string text;
            public string target;
            public string source;
        }

        public void Init(string url, string transCode, string resultCode)
        {
            _url = "http://127.0.0.1:16888/translater"; //example http://127.0.0.1:16888/translater
        }

        public string GetResult(string original, ref bool isError)
        {
            //줄바꿈은 %0A 임
            string trim = original.Replace(" ", "");
            trim = trim.Replace(Environment.NewLine, "");
            if (trim == "")
            {
                return "";
            }

            string result = "";
            var client = new RestClient(_url);
            var request = new RestRequest(Method.POST);
            request.AddHeader("content-type", "application/json"); //폼 형식
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("charset", "UTF-8");

            //Here generate a object of the JSON which  sent to server
            ToTrans toTrans = new ToTrans
            {
                name = _transCode + _resultCode,
                text = original,
                target = _resultCode,
                source = _transCode
            };

            request.AddJsonBody(toTrans);


            IRestResponse response = client.Execute(request);

            if(response == null || !response.IsSuccessful)
            {
                isError = true;
                return "error";
            }

            IDictionary<string, object> dic = (IDictionary<string, object>)SimpleJson.DeserializeObject(response.Content);

            //result example

            /*
             the return can be like this JSON:
            {
            "text": "これは翻訳インタフェースです",//the source ext
            "from": "ja", //the source text type
            "to": "en", //the destination text type
            "errorMessage": "",
            "errorCode" : 0,
            "result": ["This is a translation interface"] 
            //the result is an array of string because the source text may contain many paragraphs, 
            the proccess will be slow, so the source text should be cutoff by nextline("/n"), every paragraph can be a member of the array.
            } 
            */

            //parse error
            string errorCode ="0";
            if(dic.ContainsKey("errorCode"))
            {
                string errorCodeObject = (string)dic["errorCode"];
                if (errorCodeObject != null) 
                {
                    errorCode = errorCodeObject;
                }
            }

            if(!errorCode.Equals("0")) 
            {
                string errorResult = "error";
                if (dic.ContainsKey("errorMessage"))
                {
                    string errorMessageObject = (string)dic["errorMessage"];
                    if (errorMessageObject != null) 
                    {
                        errorResult = errorMessageObject;
                    }
                }

                isError = true;
                return errorResult;
            }

            //parse result
            if (dic.ContainsKey("result"))
            {
                JsonArray resultarray = (JsonArray)dic["result"];
                for (int i = 0; i < resultarray.Count; i++)
                    {
                        result += (string)resultarray[i];
                    }
                }   
            
            else
            {
                result = "Empty result";
            }

            return result;
        }
    }
}

**Comment by liuchuhan1** [comment]
I am weak in C#, so for the layout issue and parameter transit issue, I cant deal with them.

**Comment by killkimno** [comment]
You can find where to set it up here

![image](https://github.com/killkimno/MORT/assets/7446259/a88c7c96-a2ed-4b76-86fe-a374d86bb33b)
1. Additional tab -> Advenced Setting

![image](https://github.com/killkimno/MORT/assets/7446259/f2f4b9ee-dcbb-4ae7-a10c-60ff048cd5b0)
2. Trnaslation tab -> Custom api 
-enable adv custom api use google language code -> use Google Translate Language code, if disalbe you must set source and target code

im confuse 
This code checks whether the result is an array or a normal character type.

Any errors here?

                if (resultObject is JsonArray)
                {
                    JsonArray resultarray = (JsonArray)resultObject;
                    for (int i = 0; i < resultarray.Count; i++)
                    {
                        result += (string)resultarray[i];
                    }
                }
                else
                {
                    result = (string)resultObject;
                }


Could you please join the Discord? Then I think we can solve the problem faster.
https://discord.com/invite/ha5yNy9

**Comment by liuchuhan1** [comment]
thank you, now all can work well, the issue for me is that my model's batchsize is so low that it cant translate a large paragraph. I will fintune it tomorrow.

**Comment by killkimno** [comment]
Applied to latest version
