### ISSUE TITLE
Simplified Chinese language support

### ISSUE THREAD

**Issue by mikualpha** [killkimno/MORT#14]
It's a very useful plugin to play anime games! Thank you!

According to the description in [#11](https://github.com/killkimno/MORT/issues/11), I have translated the text to [Simplified Chinese](https://docs.google.com/spreadsheets/d/1n0eQe2WnVkcXkKm3j6r_pMjRGUAdzDkHWNr0THkUXaY) (most based on English, and partially using GPT and DeepL to translate from Korean, may have some incorrect translations).

If possible, please add Chinese translation to the interface. Thanks.

--

Additionally, I think you can consider using translation contribution tools similar to [Crowdin](https://crowdin.com/) to facilitate future software updates and multilingual support.

**Comment by killkimno** [comment]
Thank you for using MORT.
In the next update, i will apply the requested language to the interface.

But I'm not familiar with the language requested, I'll use a translator.

**Comment by killkimno** [comment]
Applied to latest version

**Comment by mikualpha** [comment]
emmm……
It looks like you didn't notice the [translation](https://docs.google.com/spreadsheets/d/1n0eQe2WnVkcXkKm3j6r_pMjRGUAdzDkHWNr0THkUXaY) I provided before? From the latest version, it looks like it uses machine translated text.

**Comment by killkimno** [comment]
sorry!
I just checked that you provided a translation.

I will apply it right away as soon as possible.
I will open the issue again

**Comment by killkimno** [comment]
Thank you
Applied to MORT 1.261!

There is no function to merge localized tables yet, so I did it manually.
Can you please check it once?

**Comment by mikualpha** [comment]
It seems to work well~ Thx!
By the way, I think it's a good choice which accessing a translate platform (like Crowdin or some else). It can guarantee the quality of multilingual translations by the community and facilitates automation.

**Comment by killkimno** [comment]
thank you! New translation methods are still being researched.
And once again, please download the latest version of MORT.

Temporarily re-updated due to problems with DeepL Translator.

I'm going to fix a few issues tonight and upload it as a full version
