### ISSUE TITLE
Index was out of range error

### ISSUE THREAD

**Issue by Dmitryqq** [killkimno/MORT#15]
Hello
Getting this error every time I open the program, clicking the "Apply" button or finishing quick setting. As the result, settings are not applying. Pic 2 is coming after the first one (it's saying application is shutting down) but nothing happens.
![image](https://github.com/killkimno/MORT/assets/32351227/7ba60e34-cd56-4fe3-9a30-6d6305a2c2ba)
![image](https://github.com/killkimno/MORT/assets/32351227/577e9044-158e-4e9e-890a-97184b8412a4)

By the way russian translate is bad and breaking the interface, how can I change it to english?

**Comment by killkimno** [comment]
hello
It seems like the app settings are messed up.

Do the following to reset and try again.
![image](https://github.com/killkimno/MORT/assets/7446259/d6ef021f-20f9-46a8-9dad-d4f6c731b5e6)

1. Additional -> Reset config


change language
![image](https://github.com/killkimno/MORT/assets/7446259/6eaf36b9-07d7-4756-869a-bf1cb4086396)

1. Additional -> Advanced settings -> App language

**Comment by Dmitryqq** [comment]
Resetting config helped, thanks. Its weird, because it was my 1st launch and already with broken config.
And that "Config file" submenu in russian looks like file setup/configuration, and the buttons are "Setting", "Save settings" and "reload".

**Comment by killkimno** [comment]
It seems that a problem occurred during the initialization process.

Thank you for reporting the worng text! I'll fix it
