### ISSUE TITLE
Request to Add EasyOCR to MORT

### ISSUE THREAD

**Issue by creature93x** [killkimno/MORT#18]
I kindly request the addition of EasyOCR to MORT. EasyOCR's impressive accuracy and multilingual support would undoubtedly enhance the functionality of MORT.

**Comment by killkimno** [comment]
Thanks to suggest!
Currently, MORT does not support Python.
Therefore, I will reserch how to use Python in c#

**Comment by killkimno** [comment]
https://blog.naver.com/killkimno/223288405115
here is development version.

**Comment by killkimno** [comment]
hello!
1.270 version available to use EasyOCR!
https://github.com/killkimno/MORT/releases/tag/1.270
