### ISSUE TITLE
virustotal

### ISSUE THREAD

**Issue by Ammar-A7med** [killkimno/MORT#22]
![image](https://github.com/killkimno/MORT/assets/94337602/34eed263-2aab-4699-8ccf-56cfda500e96)

**Comment by killkimno** [comment]
Thank you for reporting!
This problem occurred due to false positive.
I will report the false positive to the relevant antivirus.

This has happened before too
https://blog.naver.com/killkimno/221730705655

**Comment by Ammar-A7med** [comment]
> Thank you for reporting! This problem occurred due to false positive. I will report the false positive to the relevant antivirus.
> 
> If you look, only a small number of anti virus got results like that. You can think of it as a false positive.
> 
> This has happened before too https://blog.naver.com/killkimno/221730705655

I know its false positive 
I say it to report it 
keep uptade your app man its amazing ❤
