### ISSUE TITLE
Right-to-Left Text Direction for Arabic (and maybe other languages that are written from right to left)

### ISSUE THREAD

**Issue by creature93x** [killkimno/MORT#23]
Currently, the translation in the overlay is displayed as left to right text (LTR), which is not suitable for Arabic script. Arabic should be displayed from right to left (RTL) to ensure proper readability and user experience for Arabic-speaking users.

it is not enough to set alignment to right. the issue happens when there are some English words that have no direct Arabic translation so the translation ends up messy as an example for this text :

![image](https://github.com/killkimno/MORT/assets/38745587/2929fd18-fe0d-4ef8-b737-a69384941dc0)

the translation is messy and words are misplaced:

![image](https://github.com/killkimno/MORT/assets/38745587/ebe306d7-683a-4449-9cc1-53c45723e1eb)

the result should be displayed like this:

![image](https://github.com/killkimno/MORT/assets/38745587/074d75cd-fbb8-4a83-8b1c-bc24cf3430d6)

the issue should be fixed by changing the translation text direction to right-to-left before displaying the result on the overlay.

**Comment by killkimno** [comment]
hello! Thank you for your comment
ill add the  overlay window right-align function first.

However, I don't know Arabic exactly, I don't know what additional work to do, and it's difficult to determine if it's working properly.

Therefore, proper support will likely take quite some time.
It would be of great help to me if you could create the code and upload it.

**Comment by creature93x** [comment]
hello, tank you for the reply. sure i will take a look at it and try to fix it as soon as i can.

**Comment by BlackFlagXKhX** [comment]
> hello! Thank you for your comment ill add the overlay window right-align function first.
> 
> However, I don't know Arabic exactly then it's difficult to determine if it's working properly.
> 
> Therefore, proper support will likely take quite some time. It would be of great help to me if you could create the code and upload it.

I hope this site is useful to you
https://rtlstyling.com/posts/rtl-styling

**Comment by creature93x** [comment]
i did manage to fix it but it is hard coded all i needed to do is add this line sf.FormatFlags |= StringFormatFlags.DirectionRightToLeft; in TransformLayer.cs:
using (Brush foreBrush = new SolidBrush(FormManager.Instace.MyMainForm.MySettingManager.TextColor))
                {

                    sf.Alignment = stringFormat.Alignment;
                    sf.LineAlignment = stringFormat.LineAlignment;
---------->   sf.FormatFlags |= StringFormatFlags.DirectionRightToLeft;

**Comment by killkimno** [comment]
Thanks for the code!
We'll add it in the next update.
I'm trying to set it to Advanced Settings -> App Settings -> "Read translated text from right to left".

This feature can be set in advanced settings, it is the system language, and mort will try to activate automatically when you run it for the first time.

Is there a more appropriate phrase other than “read the translated text from right to left”?

And are there any languages other than Arabic that should automatically activate this feature?

**Comment by creature93x** [comment]
You're welcome! Instead of "read the translated text from right to left," you could consider using "Display text in right-to-left (RTL) format" or "Enable right-to-left (RTL) text display." These phrases are more concise and specific to the action being performed.

Regarding languages other than Arabic that may require this feature, languages such as Hebrew, Urdu, Farsi (Persian), and some others are typically written from right to left. So, it would be prudent to include these languages as well to automatically activate the RTL feature.

**Comment by killkimno** [comment]
https://drive.google.com/file/d/14VE3hniVD6Ycdry3f8eackmPi9th1Aqi/view?usp=sharing

here is RTL Test version

**Comment by BlackFlagXKhX** [comment]
> https://drive.google.com/file/d/14VE3hniVD6Ycdry3f8eackmPi9th1Aqi/view?usp=sharing
> 
> here is RTL Test version
> 
> Additional tab -> Advanced Setting -> App Setting -> General -> Display RTL Applies only to text translation results window

Hello, Firstly, I thank you for your effort
 Text from right to left in (Translation Window Type) works with "Dark" and "layer" but don't work "Overlay"
 
![Screenshot 2024-02-19 192345](https://github.com/killkimno/MORT/assets/46535005/b75ad840-3a31-415c-b9a9-9172cfdf1432)
![Screenshot 2024-02-19 192525](https://github.com/killkimno/MORT/assets/46535005/68de4184-3744-43d7-9239-f050f70b0efb)
![Screenshot 2024-02-19 192606](https://github.com/killkimno/MORT/assets/46535005/826b266d-1cd8-44da-9176-679af4dd7710)

**Comment by creature93x** [comment]
Hello, I can confirm the statement made by @BlackFlagXKhX. It functions as expected in the Dark and Layered formats but not in the Overlay format.

**Comment by killkimno** [comment]
Thank you for your feedback
ill fix it

**Comment by killkimno** [comment]
https://drive.google.com/drive/folders/1TwH758-OSy_f5Q83TAZjm9YDbUQg6Qel?usp=drive_link

Here is a version that fixed issue

**Comment by BlackFlagXKhX** [comment]
I hope you add Arabic to the DeepL translator.

**Comment by creature93x** [comment]
i can confirm that everything is working as intended thank you for your time and effort!

**Comment by killkimno** [comment]
ill add Arabic to the DeepL  next update
