### ISSUE TITLE
Text on light background

### ISSUE THREAD

**Issue by rektceb** [killkimno/MORT#24]
Hi, MORT work great with text on dark background, but do you have any trick for some games that don't have a dark background option for subtitles.
I played full story game Wild Heart with MORT and work great because game have in options dark background for subtitles

**Comment by killkimno** [comment]
hello!
You can use the image adjust function to recognize only the font.

![image](https://github.com/killkimno/MORT/assets/7446259/7130abb6-a740-4dd0-aa71-b796e34f69aa)

You can see how it was extracted by pressing the preview button.

**Comment by rektceb** [comment]
> hello! You can use the image adjust function to recognize only the font.
> 
> ![image](https://private-user-images.githubusercontent.com/7446259/296422118-7130abb6-a740-4dd0-aa71-b796e34f69aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNTY5NDQsIm5iZiI6MTcwNTE1NjY0NCwicGF0aCI6Ii83NDQ2MjU5LzI5NjQyMjExOC03MTMwYWJiNi1hNzQwLTRkZDAtYWE3MS1iNzk2ZTM0ZjY5YWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTNUMTQzNzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2FlNzBiYWY5MWI2ZDU4YzNkNzI1ODEyMDE5MGE1ZmU0ODMzMTA4ZjQxYzQ4ZjMzOTI0NWNjMzYwZmIyODE2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ATnJsLKNV6ZeOgHAfSEjwOQMFMwMgTx2OWNx-qZuerw)
> 
> You can see how it was extracted by pressing the preview button.

It still misrecognizes text in Final Fantasy XV, for example :(

**Comment by killkimno** [comment]
Please upload screenshots of a few sections that are not recognized properly.
I will check the color value and let you know.

**Comment by rektceb** [comment]
Here, for example, it will translate incorrectly.
I can here change value of Extract by Threshold, but another passage may have problem, because text can be on darker background

![Bez názvu](https://github.com/killkimno/MORT/assets/155260228/7a572177-c396-4bc0-98d9-259ca8b2db79)

**Comment by rektceb** [comment]
> Please upload screenshots of a few sections that are not recognized properly. I will check the color value and let you know.

Here, for example, it will translate incorrectly.
I can here change value of Extract by Threshold, but another passage may have problem, because text can be on darker background

![Bez názvu](https://github.com/killkimno/MORT/assets/155260228/7a572177-c396-4bc0-98d9-259ca8b2db79)

**Comment by rektceb** [comment]
And another Final Fantasy vii remake 

![Bez názvu](https://github.com/killkimno/MORT/assets/155260228/1135c03e-c44c-492e-b3b6-63e42d18d2a8)

![2](https://github.com/killkimno/MORT/assets/155260228/1da9e7e2-d184-4443-bd10-5a9483e4366f)

**Comment by killkimno** [comment]
Currently, the image is uploaded as a jpg file.
It's difficult to determine the exact font color.

I think it's probably hsv - s= 0 ~12 / v = 83~90.
Can you please upload the original screenshot?

If you upload it after visiting Discord, it will probably be uploaded as the original file.
https://discord.com/invite/ha5yNy9

**Comment by rektceb** [comment]
> Currently, the image is uploaded as a jpg file. It's difficult to determine the exact font color.
> 
> I think it's probably hsv - s= 0 ~12 / v = 83~90. Can you please upload the original screenshot?
> 
> If you upload it after visiting Discord, it will probably be uploaded as the original file. https://discord.com/invite/ha5yNy9

My understanding is that if I choose the correct font color value, ocr will capture the text on any background - does it matter if it's on a light or dark background?

**Comment by killkimno** [comment]
Of course, if there is a background that is the same as the specified color, it may not be recognized.

For example HSV S = 0-5 / V= 90-100 This value is usually a bright white font.

However, if the background is also very bright sky blue, it may fall within the above color range.
