### ISSUE TITLE
Can you add copy direct result translation to clipboard function

### ISSUE THREAD

**Issue by phamngocbach2010** [killkimno/MORT#25]
this program only make copy results Ocr, doesn't have create Translate Results to clipboard, if will be amazing if have this function, nice work pro :D

**Comment by killkimno** [comment]
Thanks for your suggestion.
ill add a function to save OCR / translation / OCR+translation to the clipboard.

**Comment by phamngocbach2010** [comment]
Thanks you so much, you should be hero of our world

**Comment by phamngocbach2010** [comment]
Thanks you so much, you are awesome

**Comment by phamngocbach2010** [comment]
Thanks you so much

**Comment by killkimno** [comment]
Feature added in 1.279v
Advanced Settings - OCR tab - Save to clipboard
