### ISSUE TITLE
There is a problem with RTL text formatting (MORT v1.277)

### ISSUE THREAD

**Issue by BlackFlagXKhX** [killkimno/MORT#35]
There is a problem in the latest version, which is the right-to-left (RTL) text direction.
The translated text appears from left to right as shown in the image

* Translation window Type: Overlay

![Screenshot 2024-04-16 040321](https://github.com/killkimno/MORT/assets/46535005/f9a880c5-46d9-4404-be93-2acc2c13ffed)

**Comment by killkimno** [comment]
Thanks to reporting issue
ill check it

**Comment by killkimno** [comment]
https://drive.google.com/drive/folders/1QZbHFLngblCVk3iATrR7CsTeid5zVRic?usp=drive_link

Here is fixed version

**Comment by BlackFlagXKhX** [comment]
> https://drive.google.com/drive/folders/1QZbHFLngblCVk3iATrR7CsTeid5zVRic?usp=drive_link
> 
> Here is fixed version

it's work 
thanks
