### ISSUE TITLE
unable to load mort_core.dll

### ISSUE THREAD

**Issue by spsdamn** [killkimno/MORT#36]
if i use mort versions later 1.239

![image](https://github.com/killkimno/MORT/assets/138528335/3cc5b608-34fe-4536-94d8-69642bdde627)
after press ok:
![image](https://github.com/killkimno/MORT/assets/138528335/e5ab329c-bf2b-48bf-bec8-346b8b7196dc)

path in traceback is different then path exe. even other disk. maybe its a problem

installed:
![image](https://github.com/killkimno/MORT/assets/138528335/2e7abed3-f616-4787-88d6-9b6d59c093f7)

**Comment by spsdamn** [comment]
![image](https://github.com/killkimno/MORT/assets/138528335/a8b0e8e4-c5fb-4d8a-a478-31790c4df350)

**Comment by killkimno** [comment]
CPU must Support AVX2. If Your CPU not support AVX2, Use 32bit version MORT instead
https://blog.naver.com/killkimno/222936631523
