### ISSUE TITLE
error in MORT

### ISSUE THREAD

**Issue by godb1lessw** [killkimno/MORT#39]
hi, today I ran into a problem when downloading MORT. I downloaded the zip file, extracted it, launched it, but after it gave these two errors, what should I do?
![Screenshot_1](https://github.com/killkimno/MORT/assets/170551712/f8200b0d-5137-4944-8d29-be5bb09b90eb)
![Screenshot_2](https://github.com/killkimno/MORT/assets/170551712/8f9b22d0-7ad1-433c-b945-81861a44986e)

**Comment by killkimno** [comment]
CPU must Support AVX2. If Your CPU not support AVX2, Use 32bit version MORT instead
https://blog.naver.com/killkimno/222936631523

**Comment by luzzz4** [comment]
its the same

**Comment by killkimno** [comment]
May i know your os version?
Mort require at least windows10

And let me know which error you get when you run the 32-bit version.

**Comment by godb1lessw** [comment]
omg Thank you very much T-T
