### ISSUE TITLE
Request for the Polish language in Google Translate

### ISSUE THREAD

**Issue by apkipc9** [killkimno/MORT#4]
Hi, could you please add the Polish language for translation through Google? The translation option through Deepl doesn't work perfectly; after some time, the languages switch automatically.
Regards.

**Comment by killkimno** [comment]
Thanks for your interest!
I'll apply it to the next version

Here is tempory use polish language

1. Open UserTransCode.txt -> UserData/UserTransCode.txt
2. Add line -> pl, Polish
3. Save UserTransCode.txt
4. Open Mort -> Translation tab -> Google Setting  -> Now you can use Polish language
5.

**Comment by apkipc9** [comment]
Thanks for your help..
I need to change like this?:

 //sample
//code list - https://cloud.google.com/translate/docs/languages?hl=en
//only support google translate
//code, display name
//it, 이탈리아어
//pl, Polish

**Comment by killkimno** [comment]
// is a comment.
Do not put it because

Change to this.
//sample
//code list - https://cloud.google.com/translate/docs/languages?hl=en
//only support google translate
//code, display name
//it, 이탈리아어
pl, Polish

**Comment by apkipc9** [comment]
I'am sory for mistake, it's works now. A Big Thanks for Your Help :)

**Comment by killkimno** [comment]
publish new version - Polish language added
