### ISSUE TITLE
[BUG] Failed to added Additonal Language (vietnamese) in WInOCR option

### ISSUE THREAD

**Issue by tukangcode** [killkimno/MORT#40]
How to repeat bug
1. Open MORT
2. Go to General Settings
3. Choose WinOCR
4. click add aditional language button (that one in korea)
5. pop up would you like to go to additional language setting windows... click ok
6. System open windows language setting
7.  Click Ad language
8. select and chose vietnam language
9. install it
10.restart to applied effect on system
11. Open MORT
12.  go to general tab
13. choose winocr
14. select language
15.  Vietnam language not being added to mort choice.

OS : windows 10 proffesional
Install additional requirement ? : yes all of it
read manual : yes all of it

**Comment by killkimno** [comment]
hello!
Not all languages support Windows OCR.
Vietnamese does not support Windows OCR

**Comment by tukangcode** [comment]
ah.... That very unfortunate teseract is not bad but it kind not work
sometime, thanks for answer.

Pada Sab, 25 Mei 2024 14.25, 몽키해드 ***@***.***> menulis:
