### ISSUE TITLE
system.dllNotFoundException: Unable to load DLL'DLL\\MORT_CORE.dll'

### ISSUE THREAD

**Issue by rememberyourwhy** [killkimno/MORT#41]
Hey i ran into a problem when trying to run the program. It is not on the error list on blog.naver.com so I dont know how to deal with it. 
Tried several things as it said something about MORT_CORE and D:\project\MORT\...:
- Checked DLL folder and MORT_CORE is there
- Checked D drive but there are no such directory there
- Also tried to move the folder from C drive to D drive but to no end. 

I couldnt install similar OCR app YomiNinja as well (doesnt work for both the app ver and the build ver) so potentially there are something wrong with my windows (got a virus attack lol, but everything else is fine) 

Here is the full error description:
"""
System.DllNotFoundException: Unable to load DLL
'DLL\\MORT_CORE.dlI' or one of its dependencies: A dynamic link
library (DLL) initialization routine failed. [0x8007045A]

at MORT.Form1.initOcr0

at MORT.Form1..ctorl] in
D:\project\MORT\64bit\MORT\MORT\Form1.cs:line 719
"""
After click OK
"""
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Form1'.

at System.Windows.Forms.Control.CreateHandle0

at System.Windows.Forms.Form.CreateHandlefl

at System.Windows.Forms.Control.get_Handle[]

at System.Windows.Forms.Contro|.SetVisibleCore[Boolean value]

at System.Windows.Forms.Form.SetVisibleCore[Boolean value]

at
System.Windows.Forms.Application.ThreadContext.RunMessageLoopln
nerlmsoloop reason, ApplicationContext context]

at
System.Windows.Forms.Application.ThreadContext.RunMessageLoop(m
soloop reason, ApplicationContext context]

at MORT.Program.RunMortl] in
D:\project\MORT\64bit\MORT\MORT\Program.cs:line 63
"""
![image](https://github.com/killkimno/MORT/assets/95213333/4cc2496b-2cb6-465c-8b2b-090500aa7418)
![image](https://github.com/killkimno/MORT/assets/95213333/3f833287-14d6-43af-a7fd-d86a4d778bed)

**Comment by killkimno** [comment]
CPU must Support AVX2. If Your CPU not support AVX2, Use 32bit version MORT instead
https://blog.naver.com/killkimno/222936631523

**Comment by rememberyourwhy** [comment]
ah thank you, as you say these i realized that sounds familiar and checked the error list again and it is on there, dont know how i read back and forth 5 times 2 days bfore and didnt see it.
