### ISSUE TITLE
How can I use this repo to do simple OCR job.

### ISSUE THREAD

**Issue by zydjohnHotmail** [killkimno/MORT#42]
Hello:
I have tried to use your repo, I have done this: git clone your_repo_url
Open it with Visual Studio 2022 (version 17.10.3)
Update 3 nuget packags to the latest version.
Build the solution, but I got 37 compiler errors.
Since I am not interested to really build this complicated project, but I want to know if I can use part of your repo to do simple OCR job.  I need the OCR job to be done locally without send big volume of images online to remote server for processing, since it is not in real time, and no privacy.
I show you a very simple and easy image, let's say its name is: "C:\Images\1.png", I show you the image as an attachment. If I can use your repo to do the OCR job, please show me the simple code for this.
Thanks,
![Number7](https://github.com/killkimno/MORT/assets/45263518/b8b55778-f74a-4212-967b-548a9a8bc634)

**Comment by killkimno** [comment]
Problems occur when some packages are updated to the latest version
current project has a complex process, there is no way to use OCR right away.

Please use the sample code provided by Tesseract/WIN OCR.
https://tesseract-ocr.github.io/tessdoc/APIExample.html
https://learn.microsoft.com/en-us/samples/microsoft/windows-universal-samples/ocr/
