### ISSUE TITLE
Korean trained data

### ISSUE THREAD

**Issue by scmanjarrez** [killkimno/MORT#5]
Hi, are you using official tesseract trained data? I'd like to use kor.traineddata, but I'm not sure if it's compatible.

https://github.com/tesseract-ocr/tessdata/blob/main/kor.traineddata

**Comment by killkimno** [comment]
yes mort use official tess data
To minimize the size, distributing only English and Japanese.

but you can use other tessdata
1. downalod tessdata
2. copy to -> MORT/tessdata folder
3. run mort

![image](https://github.com/killkimno/MORT/assets/7446259/3d27fc0f-30b8-46cb-8369-c5d08c1a2c9f)
4. use tesseract OCR, TessData - filename , Language - etc
