### ISSUE TITLE
About Image Adjust Settings

### ISSUE THREAD

**Issue by leventozz** [killkimno/MORT#57]
i recently started using mort and i have to say that it is a very successful program. but i want to ask something. when i want to use the program in yakuza 6, it is difficult to read the subtitles from ocr because they have no background. i tried several treshold and extract rgb settings but i didn't get a successful result.(i check with preview adjust result) when i stop the game, the screen gets a little darker and in this case the program translates almost perfectly. how can i find the appropriate treshold setting?

sample image: https://prnt.sc/nMgp641V2Wwf

**Comment by killkimno** [comment]
hi!
looks like hsv ->s = 0~1 / v=25 ~42

how to find adjust value
1. set ocr area first
2. MORT -> General tab -> image adjust -> click preview adjust result
3. now you can see color binary window
4. click restore then you can see original screen
5. click or drag text then you can see color value
6. input color value and conversion then you can see result

**Comment by leventozz** [comment]
Thank for reply and you are right. I was not know about that feature. It worked.
