### ISSUE TITLE
waiting attach issue

### ISSUE THREAD

**Issue by s4cta3l** [killkimno/MORT#8]
I do everything right but after i select window its still stuck at waiting attach

**Comment by killkimno** [comment]
Sometimes there may be windows that don't work.
Or sometimes it doesn't.

Have you tried it in another window?

**Comment by s4cta3l** [comment]
yes I tried chrome, blue protocol, bandai launcher.... nothing works

**Comment by killkimno** [comment]
This function is a window function, but sometimes it doesn't work
Try updating Windows
There's a case that's been solved with this

**Comment by s4cta3l** [comment]
Im on win10 1909 btw. but thx
